// ---------------------------------------------------------------- //
// This file is autogenerated by pioasm version 2.2.0; do not edit! //
// ---------------------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// ------------------ //
// quadrature_encoder //
// ------------------ //

#define quadrature_encoder_wrap_target 0
#define quadrature_encoder_wrap 27
#define quadrature_encoder_pio_version 1

#define quadrature_encoder_offset_update 21u

static const uint16_t quadrature_encoder_program_instructions[] = {
            //     .wrap_target
    0x0015, //  0: jmp    21
    0x0014, //  1: jmp    20
    0x0010, //  2: jmp    16
    0x0015, //  3: jmp    21
    0x0010, //  4: jmp    16
    0x0015, //  5: jmp    21
    0x0015, //  6: jmp    21
    0x0014, //  7: jmp    20
    0x0014, //  8: jmp    20
    0x0015, //  9: jmp    21
    0x0015, // 10: jmp    21
    0x0010, // 11: jmp    16
    0x0015, // 12: jmp    21
    0x0010, // 13: jmp    16
    0x0014, // 14: jmp    20
    0x0015, // 15: jmp    21
    0xa029, // 16: mov    x, ~x
    0x0052, // 17: jmp    x--, 18
    0xa029, // 18: mov    x, ~x
    0x0015, // 19: jmp    21
    0x0055, // 20: jmp    x--, 21
    0xa0c1, // 21: mov    isr, x
    0x4002, // 22: in     pins, 2
    0xa046, // 23: mov    y, isr
    0x8000, // 24: push   noblock
    0x6042, // 25: out    y, 2
    0x4042, // 26: in     y, 2
    0xa0a6, // 27: mov    pc, isr
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program quadrature_encoder_program = {
    .instructions = quadrature_encoder_program_instructions,
    .length = 28,
    .origin = 0,
    .pio_version = quadrature_encoder_pio_version,
#if PICO_PIO_VERSION > 0
    .used_gpio_ranges = 0x0
#endif
};

static inline pio_sm_config quadrature_encoder_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + quadrature_encoder_wrap_target, offset + quadrature_encoder_wrap);
    return c;
}

#include "hardware/clocks.h"
#include "hardware/gpio.h"
static inline void quadrature_encoder_program_init(PIO pio, uint sm, uint offset, uint pin_a) {
    pio_sm_config c = quadrature_encoder_program_get_default_config(offset);
    sm_config_set_in_pins(&c, pin_a);
    sm_config_set_in_shift(&c, false, false, 32);
    sm_config_set_out_shift(&c, true, false, 32);
    sm_config_set_clkdiv(&c, 1.0f);
    // Pin setup
    pio_gpio_init(pio, pin_a);
    pio_gpio_init(pio, pin_a + 1);
    gpio_pull_up(pin_a);
    gpio_pull_up(pin_a + 1);
    pio_sm_set_consecutive_pindirs(pio, sm, pin_a, 2, false);
    // Initialize x to 0, and shift the initial pin state into ISR
    pio_sm_exec(pio, sm, pio_encode_set(pio_x, 0));
    pio_sm_exec(pio, sm, pio_encode_in(pio_pins, 2));
    pio_sm_init(pio, sm, offset + quadrature_encoder_offset_update, &c);
    pio_sm_set_enabled(pio, sm, true);
}
static inline int32_t quadrature_encoder_get_count(PIO pio, uint sm) {
    uint32_t val;
    // Read count without disturbing state machine
    // Force an 'in' of X to ISR, then read ISR
    pio_sm_exec_wait_blocking(pio, sm, pio_encode_in(pio_x, 32));
    val = pio_sm_get_blocking(pio, sm);
    return (int32_t)val;
}
static inline void quadrature_encoder_set_count(PIO pio, uint sm, int32_t count) {
    pio_sm_exec_wait_blocking(pio, sm, pio_encode_set(pio_x, (uint32_t)count & 0x1f));
    // For counts > 31, we need multiple operations, but this is rarely needed
}

#endif

// ---------- //
// pwm_simple //
// ---------- //

#define pwm_simple_wrap_target 3
#define pwm_simple_wrap 9
#define pwm_simple_pio_version 1

static const uint16_t pwm_simple_program_instructions[] = {
    0x80a0, //  0: pull   block
    0xa027, //  1: mov    x, osr
    0xa047, //  2: mov    y, osr
            //     .wrap_target
    0x8080, //  3: pull   noblock
    0xa027, //  4: mov    x, osr
    0xe001, //  5: set    pins, 1
    0x0046, //  6: jmp    x--, 6
    0xe000, //  7: set    pins, 0
    0xe05f, //  8: set    y, 31
    0x0789, //  9: jmp    y--, 9                 [7]
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program pwm_simple_program = {
    .instructions = pwm_simple_program_instructions,
    .length = 10,
    .origin = -1,
    .pio_version = pwm_simple_pio_version,
#if PICO_PIO_VERSION > 0
    .used_gpio_ranges = 0x0
#endif
};

static inline pio_sm_config pwm_simple_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + pwm_simple_wrap_target, offset + pwm_simple_wrap);
    return c;
}

static inline void pwm_simple_program_init(PIO pio, uint sm, uint offset, uint pin) {
    pio_sm_config c = pwm_simple_program_get_default_config(offset);
    sm_config_set_set_pins(&c, pin, 1);
    sm_config_set_clkdiv(&c, 125.0f);  // 1MHz clock -> ~3.9kHz PWM
    pio_gpio_init(pio, pin);
    pio_sm_set_consecutive_pindirs(pio, sm, pin, 1, true);
    pio_sm_init(pio, sm, offset, &c);
    pio_sm_put(pio, sm, 0);  // Initial duty = 0
    pio_sm_set_enabled(pio, sm, true);
}
static inline void pwm_simple_set_duty(PIO pio, uint sm, uint8_t duty) {
    pio_sm_put(pio, sm, duty);
}

#endif

