// SPDX-License-Identifier: MIT
// DMA PID configuration for Pico 2 W (RP2350B)

#ifndef _PBDRVCONFIG_PID_DMA_RP2350_H_
#define _PBDRVCONFIG_PID_DMA_RP2350_H_

#define PBDRV_CONFIG_MOTOR_DRIVER_RP2040_DMA        (1)
#define PBDRV_CONFIG_MOTOR_DRIVER_RP2040_NUM_PORTS  (12)

#ifndef PID_DMA_MAX_MOTORS
#define PID_DMA_MAX_MOTORS 12
#endif

#endif
